"""Add Role Templates and Template Permissions

Revision ID: 140749c1ed9b
Revises: 0007_add_google_drive_to_backups
Create Date: 2026-04-13 08:27:04.556275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '140749c1ed9b'
down_revision: Union[str, None] = '0007_add_google_drive_to_backups'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_system_template', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_templates_created_at'), 'role_templates', ['created_at'], unique=False)
    op.create_index(op.f('ix_role_templates_name'), 'role_templates', ['name'], unique=True)
    op.create_table('template_permissions',
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('permission_id', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['role_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id', 'permission_id')
    )
    op.drop_index('ix_emails_created_at', table_name='emails')
    op.drop_index('ix_emails_recipient_email', table_name='emails')
    op.drop_index('ix_emails_sent_at', table_name='emails')
    op.drop_index('ix_emails_status', table_name='emails')
    op.drop_table('emails')
    op.drop_index('ix_email_templates_is_active', table_name='email_templates')
    op.drop_index('ix_email_templates_name', table_name='email_templates')
    op.drop_table('email_templates')
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_index('ix_database_backups_created_by_id', table_name='database_backups')
    op.drop_index('ix_email_verification_tokens_user_id', table_name='email_verification_tokens')
    op.create_unique_constraint(None, 'email_verification_tokens', ['user_id'])
    op.alter_column('form_links', 'allowed_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_constraint('form_links_token_key', 'form_links', type_='unique')
    op.create_index(op.f('ix_form_links_is_active'), 'form_links', ['is_active'], unique=False)
    op.create_index(op.f('ix_form_links_token'), 'form_links', ['token'], unique=True)
    op.alter_column('form_submissions', 'form_link_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('form_submissions', 'submitted_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_form_submissions_form_link_id'), 'form_submissions', ['form_link_id'], unique=False)
    op.create_index(op.f('ix_form_submissions_status'), 'form_submissions', ['status'], unique=False)
    op.drop_index('ix_password_reset_tokens_user_id', table_name='password_reset_tokens')
    op.create_unique_constraint(None, 'password_reset_tokens', ['user_id'])
    op.drop_constraint('permissions_module_action_key', 'permissions', type_='unique')
    op.drop_constraint('permissions_name_key', 'permissions', type_='unique')
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_unique_constraint('uq_module_action', 'permissions', ['module', 'action'])
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.alter_column('students', 'mobile_numbers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint('students_email_key', 'students', type_='unique')
    op.drop_constraint('students_form_submission_code_key', 'students', type_='unique')
    op.create_index(op.f('ix_students_created_at'), 'students', ['created_at'], unique=False)
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_first_name'), 'students', ['first_name'], unique=False)
    op.create_index(op.f('ix_students_form_submission_code'), 'students', ['form_submission_code'], unique=True)
    op.create_index(op.f('ix_students_is_active'), 'students', ['is_active'], unique=False)
    op.alter_column('user_widget_preferences', 'position',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('widgets', 'default_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('widgets', 'default_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('user_widget_preferences', 'position',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_students_is_active'), table_name='students')
    op.drop_index(op.f('ix_students_form_submission_code'), table_name='students')
    op.drop_index(op.f('ix_students_first_name'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_index(op.f('ix_students_created_at'), table_name='students')
    op.create_unique_constraint('students_form_submission_code_key', 'students', ['form_submission_code'])
    op.create_unique_constraint('students_email_key', 'students', ['email'])
    op.alter_column('students', 'mobile_numbers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.drop_constraint('uq_module_action', 'permissions', type_='unique')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.create_unique_constraint('permissions_name_key', 'permissions', ['name'])
    op.create_unique_constraint('permissions_module_action_key', 'permissions', ['module', 'action'])
    op.drop_constraint(None, 'password_reset_tokens', type_='unique')
    op.create_index('ix_password_reset_tokens_user_id', 'password_reset_tokens', ['user_id'], unique=True)
    op.drop_index(op.f('ix_form_submissions_status'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_form_link_id'), table_name='form_submissions')
    op.alter_column('form_submissions', 'submitted_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('form_submissions', 'form_link_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_form_links_token'), table_name='form_links')
    op.drop_index(op.f('ix_form_links_is_active'), table_name='form_links')
    op.create_unique_constraint('form_links_token_key', 'form_links', ['token'])
    op.alter_column('form_links', 'allowed_fields',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_constraint(None, 'email_verification_tokens', type_='unique')
    op.create_index('ix_email_verification_tokens_user_id', 'email_verification_tokens', ['user_id'], unique=True)
    op.create_index('ix_database_backups_created_by_id', 'database_backups', ['created_by_id'], unique=False)
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.alter_column('audit_logs', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('email_templates',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('body_html', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('variables', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='email_templates_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_email_templates_name', 'email_templates', ['name'], unique=True)
    op.create_index('ix_email_templates_is_active', 'email_templates', ['is_active'], unique=False)
    op.create_table('emails',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('recipient_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('recipient_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('body_html', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], name='emails_template_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='emails_pkey')
    )
    op.create_index('ix_emails_status', 'emails', ['status'], unique=False)
    op.create_index('ix_emails_sent_at', 'emails', ['sent_at'], unique=False)
    op.create_index('ix_emails_recipient_email', 'emails', ['recipient_email'], unique=False)
    op.create_index('ix_emails_created_at', 'emails', ['created_at'], unique=False)
    op.drop_table('template_permissions')
    op.drop_index(op.f('ix_role_templates_name'), table_name='role_templates')
    op.drop_index(op.f('ix_role_templates_created_at'), table_name='role_templates')
    op.drop_table('role_templates')
    # ### end Alembic commands ###
